on: push # runs when ever there is a push to any branch of the repo
name: A workflow for my Hello Actor Action
jobs:
  build:
    name: Hello actor action
    runs-on: ubuntu-latest # useful environment to we can run a simple bash    
    steps:
    - name: hello-actor
      run: |
        echo "hello $GITHUB_ACTOR"
